### ISSUE TITLE
suppport of BigQuery

### ISSUE THREAD

**Issue by tiozab** [darwin-eu/CDMConnector#18]
when do you expect that CDMConnector will support BigQuery?

**Comment by ablack3** [comment]
There is currently no timeline for adding bigquery tests just because there are so many other things to do and no Darwin data partner is using bigquery. Some functionality will work but not all tests are passing on bigquery. Bigquery users can try out the package and open issues which would help identify where tests are lacking.

**Comment by ablack3** [comment]
@edward-burn do you expect we will have darwin data partners on bigquery in the future?

**Comment by edward-burn** [comment]
@ablack3 I guess it depends on whether you want CDMConnector to be more widely adopted in ohdsi or not? 

I don't think there is any imminent darwin data partner that will use it (unless @MaximMoinat says otherwise), but I know there are ohdsi collaborators using big query who would like to use the tools that depend on CDMConnector. It would be good to know whether you are planning to support it here in CDMConnector or not, as if not it would of course be possible for someone to create a package that provides a means of making a cdm reference with big query

**Comment by ablack3** [comment]
Moving this discussion to the darwin-eu-dev repo. Personally I'd like to see it working with bigrquery or DatabaseConnector and some functionality does work but I think there are still a few things that don't work.
